### YamlMime:ManagedReference
items:
- uid: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery
  commentId: T:CalorieTracker.Application.Auth.Queries.GetProductByIdQuery
  id: GetProductByIdQuery
  parent: CalorieTracker.Application.Auth.Queries
  children:
  - CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.#ctor(System.Guid)
  - CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.Id
  langs:
  - csharp
  - vb
  name: GetProductByIdQuery
  nameWithType: GetProductByIdQuery
  fullName: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery
  type: Class
  source:
    remote:
      path: src/CalorieTracker.Application/Products/Queries/GetProductByIdQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: GetProductByIdQuery
    path: ../src/CalorieTracker.Application/Products/Queries/GetProductByIdQuery.cs
    startLine: 14
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Queries
  summary: >-
    Rekord reprezentujący zapytanie o pobranie produktu na podstawie jego identyfikatora.

    Przenosi dane potrzebne do jednoznacznej identyfikacji produktu w systemie.
  remarks: >-
    Wykorzystuje typ record, który zapewnia niezmienność (immutability) i jest optymalny 

    dla obiektów transferu danych (DTO). Identyfikator produktu jest typu Guid, co gwarantuje

    jego unikalność w systemie.
  example: []
  syntax:
    content: 'public record GetProductByIdQuery : IEquatable<GetProductByIdQuery>'
    content.vb: Public Class GetProductByIdQuery Implements IEquatable(Of GetProductByIdQuery)
  inheritance:
  - System.Object
  implements:
  - System.IEquatable{CalorieTracker.Application.Auth.Queries.GetProductByIdQuery}
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.#ctor(System.Guid)
  commentId: M:CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.#ctor(System.Guid)
  id: '#ctor(System.Guid)'
  parent: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery
  langs:
  - csharp
  - vb
  name: GetProductByIdQuery(Guid)
  nameWithType: GetProductByIdQuery.GetProductByIdQuery(Guid)
  fullName: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.GetProductByIdQuery(System.Guid)
  type: Constructor
  source:
    remote:
      path: src/CalorieTracker.Application/Products/Queries/GetProductByIdQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: .ctor
    path: ../src/CalorieTracker.Application/Products/Queries/GetProductByIdQuery.cs
    startLine: 14
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Queries
  summary: >-
    Rekord reprezentujący zapytanie o pobranie produktu na podstawie jego identyfikatora.

    Przenosi dane potrzebne do jednoznacznej identyfikacji produktu w systemie.
  remarks: >-
    Wykorzystuje typ record, który zapewnia niezmienność (immutability) i jest optymalny 

    dla obiektów transferu danych (DTO). Identyfikator produktu jest typu Guid, co gwarantuje

    jego unikalność w systemie.
  example: []
  syntax:
    content: public GetProductByIdQuery(Guid Id)
    parameters:
    - id: Id
      type: System.Guid
    content.vb: Public Sub New(Id As Guid)
  overload: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.#ctor*
  nameWithType.vb: GetProductByIdQuery.New(Guid)
  fullName.vb: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.New(System.Guid)
  name.vb: New(Guid)
- uid: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.Id
  commentId: P:CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.Id
  id: Id
  parent: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: GetProductByIdQuery.Id
  fullName: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.Id
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Products/Queries/GetProductByIdQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Id
    path: ../src/CalorieTracker.Application/Products/Queries/GetProductByIdQuery.cs
    startLine: 22
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Queries
  summary: Unikalny identyfikator produktu do wyszukania.
  example: []
  syntax:
    content: public Guid Id { get; init; }
    parameters: []
    return:
      type: System.Guid
      description: Wartość Guid reprezentująca unikalny klucz produktu w systemie.
    content.vb: Public Property Id As Guid
  overload: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.Id*
references:
- uid: CalorieTracker.Application.Auth.Queries
  commentId: N:CalorieTracker.Application.Auth.Queries
  href: CalorieTracker.html
  name: CalorieTracker.Application.Auth.Queries
  nameWithType: CalorieTracker.Application.Auth.Queries
  fullName: CalorieTracker.Application.Auth.Queries
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Queries
    name: Queries
    href: CalorieTracker.Application.Auth.Queries.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Queries
    name: Queries
    href: CalorieTracker.Application.Auth.Queries.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.IEquatable{CalorieTracker.Application.Auth.Queries.GetProductByIdQuery}
  commentId: T:System.IEquatable{CalorieTracker.Application.Auth.Queries.GetProductByIdQuery}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<GetProductByIdQuery>
  nameWithType: IEquatable<GetProductByIdQuery>
  fullName: System.IEquatable<CalorieTracker.Application.Auth.Queries.GetProductByIdQuery>
  nameWithType.vb: IEquatable(Of GetProductByIdQuery)
  fullName.vb: System.IEquatable(Of CalorieTracker.Application.Auth.Queries.GetProductByIdQuery)
  name.vb: IEquatable(Of GetProductByIdQuery)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery
    name: GetProductByIdQuery
    href: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.html
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery
    name: GetProductByIdQuery
    href: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.html
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.#ctor*
  commentId: Overload:CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.#ctor
  href: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.html#CalorieTracker_Application_Auth_Queries_GetProductByIdQuery__ctor_System_Guid_
  name: GetProductByIdQuery
  nameWithType: GetProductByIdQuery.GetProductByIdQuery
  fullName: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.GetProductByIdQuery
  nameWithType.vb: GetProductByIdQuery.New
  fullName.vb: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.New
  name.vb: New
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.Id*
  commentId: Overload:CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.Id
  href: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.html#CalorieTracker_Application_Auth_Queries_GetProductByIdQuery_Id
  name: Id
  nameWithType: GetProductByIdQuery.Id
  fullName: CalorieTracker.Application.Auth.Queries.GetProductByIdQuery.Id
