### YamlMime:ManagedReference
items:
- uid: CalorieTracker.Application.Auth.Handlers.LogoutHandler
  commentId: T:CalorieTracker.Application.Auth.Handlers.LogoutHandler
  id: LogoutHandler
  parent: CalorieTracker.Application.Auth.Handlers
  children:
  - CalorieTracker.Application.Auth.Handlers.LogoutHandler.#ctor(CalorieTracker.Application.Interfaces.IAppDbContext)
  - CalorieTracker.Application.Auth.Handlers.LogoutHandler.Handle(CalorieTracker.Application.Auth.Commands.LogoutCommand)
  langs:
  - csharp
  - vb
  name: LogoutHandler
  nameWithType: LogoutHandler
  fullName: CalorieTracker.Application.Auth.Handlers.LogoutHandler
  type: Class
  source:
    remote:
      path: src/CalorieTracker.Application/Auth/Handlers/LogoutHandler.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: LogoutHandler
    path: ../src/CalorieTracker.Application/Auth/Handlers/LogoutHandler.cs
    startLine: 13
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Handlers
  summary: >-
    Handler odpowiedzialny za proces wylogowania użytkownika.

    Unieważnia token odświeżający, uniemożliwiając jego ponowne użycie do uwierzytelniania.
  example: []
  syntax:
    content: public class LogoutHandler
    content.vb: Public Class LogoutHandler
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CalorieTracker.Application.Auth.Handlers.LogoutHandler.#ctor(CalorieTracker.Application.Interfaces.IAppDbContext)
  commentId: M:CalorieTracker.Application.Auth.Handlers.LogoutHandler.#ctor(CalorieTracker.Application.Interfaces.IAppDbContext)
  id: '#ctor(CalorieTracker.Application.Interfaces.IAppDbContext)'
  parent: CalorieTracker.Application.Auth.Handlers.LogoutHandler
  langs:
  - csharp
  - vb
  name: LogoutHandler(IAppDbContext)
  nameWithType: LogoutHandler.LogoutHandler(IAppDbContext)
  fullName: CalorieTracker.Application.Auth.Handlers.LogoutHandler.LogoutHandler(CalorieTracker.Application.Interfaces.IAppDbContext)
  type: Constructor
  source:
    remote:
      path: src/CalorieTracker.Application/Auth/Handlers/LogoutHandler.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: .ctor
    path: ../src/CalorieTracker.Application/Auth/Handlers/LogoutHandler.cs
    startLine: 24
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Handlers
  summary: Inicjalizuje nową instancję handlera wylogowania.
  example: []
  syntax:
    content: public LogoutHandler(IAppDbContext db)
    parameters:
    - id: db
      type: CalorieTracker.Application.Interfaces.IAppDbContext
      description: Kontekst bazy danych <xref href="CalorieTracker.Application.Interfaces.IAppDbContext" data-throw-if-not-resolved="false"></xref>.
    content.vb: Public Sub New(db As IAppDbContext)
  overload: CalorieTracker.Application.Auth.Handlers.LogoutHandler.#ctor*
  nameWithType.vb: LogoutHandler.New(IAppDbContext)
  fullName.vb: CalorieTracker.Application.Auth.Handlers.LogoutHandler.New(CalorieTracker.Application.Interfaces.IAppDbContext)
  name.vb: New(IAppDbContext)
- uid: CalorieTracker.Application.Auth.Handlers.LogoutHandler.Handle(CalorieTracker.Application.Auth.Commands.LogoutCommand)
  commentId: M:CalorieTracker.Application.Auth.Handlers.LogoutHandler.Handle(CalorieTracker.Application.Auth.Commands.LogoutCommand)
  id: Handle(CalorieTracker.Application.Auth.Commands.LogoutCommand)
  parent: CalorieTracker.Application.Auth.Handlers.LogoutHandler
  langs:
  - csharp
  - vb
  name: Handle(LogoutCommand)
  nameWithType: LogoutHandler.Handle(LogoutCommand)
  fullName: CalorieTracker.Application.Auth.Handlers.LogoutHandler.Handle(CalorieTracker.Application.Auth.Commands.LogoutCommand)
  type: Method
  source:
    remote:
      path: src/CalorieTracker.Application/Auth/Handlers/LogoutHandler.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Handle
    path: ../src/CalorieTracker.Application/Auth/Handlers/LogoutHandler.cs
    startLine: 31
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Handlers
  summary: Główna metoda handlera wykonująca unieważnienie tokena odświeżającego.
  example: []
  syntax:
    content: public Task Handle(LogoutCommand cmd)
    parameters:
    - id: cmd
      type: CalorieTracker.Application.Auth.Commands.LogoutCommand
      description: Komenda <xref href="CalorieTracker.Application.Auth.Commands.LogoutCommand" data-throw-if-not-resolved="false"></xref> zawierająca token do unieważnienia.
    return:
      type: System.Threading.Tasks.Task
      description: Task reprezentujący operację asynchroniczną.
    content.vb: Public Function Handle(cmd As LogoutCommand) As Task
  overload: CalorieTracker.Application.Auth.Handlers.LogoutHandler.Handle*
references:
- uid: CalorieTracker.Application.Auth.Handlers
  commentId: N:CalorieTracker.Application.Auth.Handlers
  href: CalorieTracker.html
  name: CalorieTracker.Application.Auth.Handlers
  nameWithType: CalorieTracker.Application.Auth.Handlers
  fullName: CalorieTracker.Application.Auth.Handlers
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Handlers
    name: Handlers
    href: CalorieTracker.Application.Auth.Handlers.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Handlers
    name: Handlers
    href: CalorieTracker.Application.Auth.Handlers.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CalorieTracker.Application.Interfaces.IAppDbContext
  commentId: T:CalorieTracker.Application.Interfaces.IAppDbContext
  parent: CalorieTracker.Application.Interfaces
  href: CalorieTracker.Application.Interfaces.IAppDbContext.html
  name: IAppDbContext
  nameWithType: IAppDbContext
  fullName: CalorieTracker.Application.Interfaces.IAppDbContext
- uid: CalorieTracker.Application.Auth.Handlers.LogoutHandler.#ctor*
  commentId: Overload:CalorieTracker.Application.Auth.Handlers.LogoutHandler.#ctor
  href: CalorieTracker.Application.Auth.Handlers.LogoutHandler.html#CalorieTracker_Application_Auth_Handlers_LogoutHandler__ctor_CalorieTracker_Application_Interfaces_IAppDbContext_
  name: LogoutHandler
  nameWithType: LogoutHandler.LogoutHandler
  fullName: CalorieTracker.Application.Auth.Handlers.LogoutHandler.LogoutHandler
  nameWithType.vb: LogoutHandler.New
  fullName.vb: CalorieTracker.Application.Auth.Handlers.LogoutHandler.New
  name.vb: New
- uid: CalorieTracker.Application.Interfaces
  commentId: N:CalorieTracker.Application.Interfaces
  href: CalorieTracker.html
  name: CalorieTracker.Application.Interfaces
  nameWithType: CalorieTracker.Application.Interfaces
  fullName: CalorieTracker.Application.Interfaces
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Interfaces
    name: Interfaces
    href: CalorieTracker.Application.Interfaces.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Interfaces
    name: Interfaces
    href: CalorieTracker.Application.Interfaces.html
- uid: CalorieTracker.Application.Auth.Commands.LogoutCommand
  commentId: T:CalorieTracker.Application.Auth.Commands.LogoutCommand
  parent: CalorieTracker.Application.Auth.Commands
  href: CalorieTracker.Application.Auth.Commands.LogoutCommand.html
  name: LogoutCommand
  nameWithType: LogoutCommand
  fullName: CalorieTracker.Application.Auth.Commands.LogoutCommand
- uid: CalorieTracker.Application.Auth.Handlers.LogoutHandler.Handle*
  commentId: Overload:CalorieTracker.Application.Auth.Handlers.LogoutHandler.Handle
  href: CalorieTracker.Application.Auth.Handlers.LogoutHandler.html#CalorieTracker_Application_Auth_Handlers_LogoutHandler_Handle_CalorieTracker_Application_Auth_Commands_LogoutCommand_
  name: Handle
  nameWithType: LogoutHandler.Handle
  fullName: CalorieTracker.Application.Auth.Handlers.LogoutHandler.Handle
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: CalorieTracker.Application.Auth.Commands
  commentId: N:CalorieTracker.Application.Auth.Commands
  href: CalorieTracker.html
  name: CalorieTracker.Application.Auth.Commands
  nameWithType: CalorieTracker.Application.Auth.Commands
  fullName: CalorieTracker.Application.Auth.Commands
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Commands
    name: Commands
    href: CalorieTracker.Application.Auth.Commands.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Commands
    name: Commands
    href: CalorieTracker.Application.Auth.Commands.html
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
