### YamlMime:ManagedReference
items:
- uid: CalorieTracker.Application.Auth.Commands.RegisterUserCommand
  commentId: T:CalorieTracker.Application.Auth.Commands.RegisterUserCommand
  id: RegisterUserCommand
  parent: CalorieTracker.Application.Auth.Commands
  children:
  - CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Email
  - CalorieTracker.Application.Auth.Commands.RegisterUserCommand.FirstName
  - CalorieTracker.Application.Auth.Commands.RegisterUserCommand.LastName
  - CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Password
  langs:
  - csharp
  - vb
  name: RegisterUserCommand
  nameWithType: RegisterUserCommand
  fullName: CalorieTracker.Application.Auth.Commands.RegisterUserCommand
  type: Class
  source:
    remote:
      path: src/CalorieTracker.Application/Auth/Commands/RegisterUserCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: RegisterUserCommand
    path: ../src/CalorieTracker.Application/Auth/Commands/RegisterUserCommand.cs
    startLine: 15
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Commands
  summary: >-
    Klasa reprezentująca komendę rejestracji nowego użytkownika.

    Zawiera wszystkie niezbędne dane wymagane do utworzenia nowego konta użytkownika.
  example: []
  syntax:
    content: public class RegisterUserCommand
    content.vb: Public Class RegisterUserCommand
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Email
  commentId: P:CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Email
  id: Email
  parent: CalorieTracker.Application.Auth.Commands.RegisterUserCommand
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: RegisterUserCommand.Email
  fullName: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Email
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Auth/Commands/RegisterUserCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Email
    path: ../src/CalorieTracker.Application/Auth/Commands/RegisterUserCommand.cs
    startLine: 20
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Commands
  summary: Adres e-mail użytkownika. Wymagany do rejestracji.
  example: []
  syntax:
    content: public string Email { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Email As String
  overload: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Email*
- uid: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Password
  commentId: P:CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Password
  id: Password
  parent: CalorieTracker.Application.Auth.Commands.RegisterUserCommand
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: RegisterUserCommand.Password
  fullName: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Password
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Auth/Commands/RegisterUserCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Password
    path: ../src/CalorieTracker.Application/Auth/Commands/RegisterUserCommand.cs
    startLine: 25
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Commands
  summary: Hasło użytkownika. Wymagane do rejestracji.
  example: []
  syntax:
    content: public string Password { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Password As String
  overload: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Password*
- uid: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.FirstName
  commentId: P:CalorieTracker.Application.Auth.Commands.RegisterUserCommand.FirstName
  id: FirstName
  parent: CalorieTracker.Application.Auth.Commands.RegisterUserCommand
  langs:
  - csharp
  - vb
  name: FirstName
  nameWithType: RegisterUserCommand.FirstName
  fullName: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.FirstName
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Auth/Commands/RegisterUserCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: FirstName
    path: ../src/CalorieTracker.Application/Auth/Commands/RegisterUserCommand.cs
    startLine: 30
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Commands
  summary: Imię użytkownika. Opcjonalne pole.
  example: []
  syntax:
    content: public string? FirstName { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property FirstName As String
  overload: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.FirstName*
- uid: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.LastName
  commentId: P:CalorieTracker.Application.Auth.Commands.RegisterUserCommand.LastName
  id: LastName
  parent: CalorieTracker.Application.Auth.Commands.RegisterUserCommand
  langs:
  - csharp
  - vb
  name: LastName
  nameWithType: RegisterUserCommand.LastName
  fullName: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.LastName
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Auth/Commands/RegisterUserCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: LastName
    path: ../src/CalorieTracker.Application/Auth/Commands/RegisterUserCommand.cs
    startLine: 35
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Commands
  summary: Nazwisko użytkownika. Opcjonalne pole.
  example: []
  syntax:
    content: public string? LastName { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LastName As String
  overload: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.LastName*
references:
- uid: CalorieTracker.Application.Auth.Commands
  commentId: N:CalorieTracker.Application.Auth.Commands
  href: CalorieTracker.html
  name: CalorieTracker.Application.Auth.Commands
  nameWithType: CalorieTracker.Application.Auth.Commands
  fullName: CalorieTracker.Application.Auth.Commands
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Commands
    name: Commands
    href: CalorieTracker.Application.Auth.Commands.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Commands
    name: Commands
    href: CalorieTracker.Application.Auth.Commands.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Email*
  commentId: Overload:CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Email
  href: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.html#CalorieTracker_Application_Auth_Commands_RegisterUserCommand_Email
  name: Email
  nameWithType: RegisterUserCommand.Email
  fullName: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Email
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Password*
  commentId: Overload:CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Password
  href: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.html#CalorieTracker_Application_Auth_Commands_RegisterUserCommand_Password
  name: Password
  nameWithType: RegisterUserCommand.Password
  fullName: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.Password
- uid: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.FirstName*
  commentId: Overload:CalorieTracker.Application.Auth.Commands.RegisterUserCommand.FirstName
  href: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.html#CalorieTracker_Application_Auth_Commands_RegisterUserCommand_FirstName
  name: FirstName
  nameWithType: RegisterUserCommand.FirstName
  fullName: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.FirstName
- uid: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.LastName*
  commentId: Overload:CalorieTracker.Application.Auth.Commands.RegisterUserCommand.LastName
  href: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.html#CalorieTracker_Application_Auth_Commands_RegisterUserCommand_LastName
  name: LastName
  nameWithType: RegisterUserCommand.LastName
  fullName: CalorieTracker.Application.Auth.Commands.RegisterUserCommand.LastName
