### YamlMime:ManagedReference
items:
- uid: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery
  commentId: T:CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery
  id: GetAllRecipesQuery
  parent: CalorieTracker.Application.Recipes.Queries
  children:
  - CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Skip
  - CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Take
  langs:
  - csharp
  - vb
  name: GetAllRecipesQuery
  nameWithType: GetAllRecipesQuery
  fullName: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery
  type: Class
  source:
    remote:
      path: src/CalorieTracker.Application/Recipes/Queries/GetAllRecipesQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: GetAllRecipesQuery
    path: ../src/CalorieTracker.Application/Recipes/Queries/GetAllRecipesQuery.cs
    startLine: 15
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Recipes.Queries
  summary: >-
    Klasa reprezentująca zapytanie o globalną listę przepisów.

    Zawiera parametry paginacji do kontroli ilości zwracanych wyników.
  example: []
  syntax:
    content: public class GetAllRecipesQuery
    content.vb: Public Class GetAllRecipesQuery
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Skip
  commentId: P:CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Skip
  id: Skip
  parent: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery
  langs:
  - csharp
  - vb
  name: Skip
  nameWithType: GetAllRecipesQuery.Skip
  fullName: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Skip
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Recipes/Queries/GetAllRecipesQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Skip
    path: ../src/CalorieTracker.Application/Recipes/Queries/GetAllRecipesQuery.cs
    startLine: 21
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Recipes.Queries
  summary: >-
    Liczba przepisów do pominięcia (stronicowanie).

    Domyślnie 0 - zaczyna od początku listy.
  example: []
  syntax:
    content: public int Skip { get; init; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Skip As Integer
  overload: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Skip*
- uid: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Take
  commentId: P:CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Take
  id: Take
  parent: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery
  langs:
  - csharp
  - vb
  name: Take
  nameWithType: GetAllRecipesQuery.Take
  fullName: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Take
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Recipes/Queries/GetAllRecipesQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Take
    path: ../src/CalorieTracker.Application/Recipes/Queries/GetAllRecipesQuery.cs
    startLine: 27
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Recipes.Queries
  summary: >-
    Maksymalna liczba przepisów do zwrócenia.

    Domyślnie 20 - rozsądny kompromis między wydajnością a użytecznością.
  example: []
  syntax:
    content: public int Take { get; init; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Take As Integer
  overload: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Take*
references:
- uid: CalorieTracker.Application.Recipes.Queries
  commentId: N:CalorieTracker.Application.Recipes.Queries
  href: CalorieTracker.html
  name: CalorieTracker.Application.Recipes.Queries
  nameWithType: CalorieTracker.Application.Recipes.Queries
  fullName: CalorieTracker.Application.Recipes.Queries
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Recipes
    name: Recipes
    href: CalorieTracker.Application.Recipes.html
  - name: .
  - uid: CalorieTracker.Application.Recipes.Queries
    name: Queries
    href: CalorieTracker.Application.Recipes.Queries.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Recipes
    name: Recipes
    href: CalorieTracker.Application.Recipes.html
  - name: .
  - uid: CalorieTracker.Application.Recipes.Queries
    name: Queries
    href: CalorieTracker.Application.Recipes.Queries.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Skip*
  commentId: Overload:CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Skip
  href: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.html#CalorieTracker_Application_Recipes_Queries_GetAllRecipesQuery_Skip
  name: Skip
  nameWithType: GetAllRecipesQuery.Skip
  fullName: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Skip
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Take*
  commentId: Overload:CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Take
  href: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.html#CalorieTracker_Application_Recipes_Queries_GetAllRecipesQuery_Take
  name: Take
  nameWithType: GetAllRecipesQuery.Take
  fullName: CalorieTracker.Application.Recipes.Queries.GetAllRecipesQuery.Take
