### YamlMime:ManagedReference
items:
- uid: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand
  commentId: T:CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand
  id: DeleteRecipeCommand
  parent: CalorieTracker.Application.Recipes.Commands
  children:
  - CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.#ctor(System.Guid,System.String)
  - CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.DeletedByUserId
  - CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.Id
  langs:
  - csharp
  - vb
  name: DeleteRecipeCommand
  nameWithType: DeleteRecipeCommand
  fullName: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand
  type: Class
  source:
    remote:
      path: src/CalorieTracker.Application/Recipes/Commands/DeleteRecipeCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: DeleteRecipeCommand
    path: ../src/CalorieTracker.Application/Recipes/Commands/DeleteRecipeCommand.cs
    startLine: 19
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Recipes.Commands
  summary: >-
    Rekord reprezentujący komendę usuwania przepisu kulinarnego.

    Zawiera identyfikator przepisu oraz informację o użytkowniku wykonującym operację.
  remarks: >-
    Wykorzystanie typu record gwarantuje niezmienność danych transferowych.

    Komenda powinna być poprzedzona weryfikacją uprawnień użytkownika.
  example: []
  syntax:
    content: 'public record DeleteRecipeCommand : IEquatable<DeleteRecipeCommand>'
    content.vb: Public Class DeleteRecipeCommand Implements IEquatable(Of DeleteRecipeCommand)
  inheritance:
  - System.Object
  implements:
  - System.IEquatable{CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand}
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.#ctor(System.Guid,System.String)
  commentId: M:CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.#ctor(System.Guid,System.String)
  id: '#ctor(System.Guid,System.String)'
  parent: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand
  langs:
  - csharp
  - vb
  name: DeleteRecipeCommand(Guid, string)
  nameWithType: DeleteRecipeCommand.DeleteRecipeCommand(Guid, string)
  fullName: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.DeleteRecipeCommand(System.Guid, string)
  type: Constructor
  source:
    remote:
      path: src/CalorieTracker.Application/Recipes/Commands/DeleteRecipeCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: .ctor
    path: ../src/CalorieTracker.Application/Recipes/Commands/DeleteRecipeCommand.cs
    startLine: 19
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Recipes.Commands
  summary: >-
    Rekord reprezentujący komendę usuwania przepisu kulinarnego.

    Zawiera identyfikator przepisu oraz informację o użytkowniku wykonującym operację.
  remarks: >-
    Wykorzystanie typu record gwarantuje niezmienność danych transferowych.

    Komenda powinna być poprzedzona weryfikacją uprawnień użytkownika.
  example: []
  syntax:
    content: public DeleteRecipeCommand(Guid Id, string DeletedByUserId)
    parameters:
    - id: Id
      type: System.Guid
    - id: DeletedByUserId
      type: System.String
    content.vb: Public Sub New(Id As Guid, DeletedByUserId As String)
  overload: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.#ctor*
  nameWithType.vb: DeleteRecipeCommand.New(Guid, String)
  fullName.vb: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.New(System.Guid, String)
  name.vb: New(Guid, String)
- uid: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.Id
  commentId: P:CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.Id
  id: Id
  parent: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: DeleteRecipeCommand.Id
  fullName: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.Id
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Recipes/Commands/DeleteRecipeCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Id
    path: ../src/CalorieTracker.Application/Recipes/Commands/DeleteRecipeCommand.cs
    startLine: 26
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Recipes.Commands
  syntax:
    content: public Guid Id { get; init; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.Id*
- uid: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.DeletedByUserId
  commentId: P:CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.DeletedByUserId
  id: DeletedByUserId
  parent: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand
  langs:
  - csharp
  - vb
  name: DeletedByUserId
  nameWithType: DeleteRecipeCommand.DeletedByUserId
  fullName: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.DeletedByUserId
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Recipes/Commands/DeleteRecipeCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: DeletedByUserId
    path: ../src/CalorieTracker.Application/Recipes/Commands/DeleteRecipeCommand.cs
    startLine: 35
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Recipes.Commands
  syntax:
    content: public string DeletedByUserId { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property DeletedByUserId As String
  overload: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.DeletedByUserId*
references:
- uid: CalorieTracker.Application.Recipes.Commands
  commentId: N:CalorieTracker.Application.Recipes.Commands
  href: CalorieTracker.html
  name: CalorieTracker.Application.Recipes.Commands
  nameWithType: CalorieTracker.Application.Recipes.Commands
  fullName: CalorieTracker.Application.Recipes.Commands
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Recipes
    name: Recipes
    href: CalorieTracker.Application.Recipes.html
  - name: .
  - uid: CalorieTracker.Application.Recipes.Commands
    name: Commands
    href: CalorieTracker.Application.Recipes.Commands.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Recipes
    name: Recipes
    href: CalorieTracker.Application.Recipes.html
  - name: .
  - uid: CalorieTracker.Application.Recipes.Commands
    name: Commands
    href: CalorieTracker.Application.Recipes.Commands.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.IEquatable{CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand}
  commentId: T:System.IEquatable{CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<DeleteRecipeCommand>
  nameWithType: IEquatable<DeleteRecipeCommand>
  fullName: System.IEquatable<CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand>
  nameWithType.vb: IEquatable(Of DeleteRecipeCommand)
  fullName.vb: System.IEquatable(Of CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand)
  name.vb: IEquatable(Of DeleteRecipeCommand)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand
    name: DeleteRecipeCommand
    href: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.html
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand
    name: DeleteRecipeCommand
    href: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.html
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.#ctor*
  commentId: Overload:CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.#ctor
  href: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.html#CalorieTracker_Application_Recipes_Commands_DeleteRecipeCommand__ctor_System_Guid_System_String_
  name: DeleteRecipeCommand
  nameWithType: DeleteRecipeCommand.DeleteRecipeCommand
  fullName: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.DeleteRecipeCommand
  nameWithType.vb: DeleteRecipeCommand.New
  fullName.vb: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.New
  name.vb: New
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.Id*
  commentId: Overload:CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.Id
  href: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.html#CalorieTracker_Application_Recipes_Commands_DeleteRecipeCommand_Id
  name: Id
  nameWithType: DeleteRecipeCommand.Id
  fullName: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.Id
- uid: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.DeletedByUserId*
  commentId: Overload:CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.DeletedByUserId
  href: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.html#CalorieTracker_Application_Recipes_Commands_DeleteRecipeCommand_DeletedByUserId
  name: DeletedByUserId
  nameWithType: DeleteRecipeCommand.DeletedByUserId
  fullName: CalorieTracker.Application.Recipes.Commands.DeleteRecipeCommand.DeletedByUserId
