### YamlMime:ManagedReference
items:
- uid: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery
  commentId: T:CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery
  id: GetLatestWeightMeasurementQuery
  parent: CalorieTracker.Application.WeightMeasurements.Queries
  children:
  - CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.#ctor(System.String)
  - CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.UserId
  langs:
  - csharp
  - vb
  name: GetLatestWeightMeasurementQuery
  nameWithType: GetLatestWeightMeasurementQuery
  fullName: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery
  type: Class
  source:
    remote:
      path: src/CalorieTracker.Application/WeightMeasurements/Queries/GetLatestWeightMeasurementQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: GetLatestWeightMeasurementQuery
    path: ../src/CalorieTracker.Application/WeightMeasurements/Queries/GetLatestWeightMeasurementQuery.cs
    startLine: 15
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.WeightMeasurements.Queries
  summary: >-
    Rekord reprezentujący zapytanie o najnowszy pomiar wagi użytkownika.

    Przenosi identyfikator użytkownika, dla którego ma zostać pobrany pomiar.
  example: []
  syntax:
    content: 'public record GetLatestWeightMeasurementQuery : IEquatable<GetLatestWeightMeasurementQuery>'
    content.vb: Public Class GetLatestWeightMeasurementQuery Implements IEquatable(Of GetLatestWeightMeasurementQuery)
  inheritance:
  - System.Object
  implements:
  - System.IEquatable{CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery}
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.#ctor(System.String)
  commentId: M:CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery
  langs:
  - csharp
  - vb
  name: GetLatestWeightMeasurementQuery(string)
  nameWithType: GetLatestWeightMeasurementQuery.GetLatestWeightMeasurementQuery(string)
  fullName: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.GetLatestWeightMeasurementQuery(string)
  type: Constructor
  source:
    remote:
      path: src/CalorieTracker.Application/WeightMeasurements/Queries/GetLatestWeightMeasurementQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: .ctor
    path: ../src/CalorieTracker.Application/WeightMeasurements/Queries/GetLatestWeightMeasurementQuery.cs
    startLine: 15
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.WeightMeasurements.Queries
  summary: >-
    Rekord reprezentujący zapytanie o najnowszy pomiar wagi użytkownika.

    Przenosi identyfikator użytkownika, dla którego ma zostać pobrany pomiar.
  example: []
  syntax:
    content: public GetLatestWeightMeasurementQuery(string UserId)
    parameters:
    - id: UserId
      type: System.String
    content.vb: Public Sub New(UserId As String)
  overload: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.#ctor*
  nameWithType.vb: GetLatestWeightMeasurementQuery.New(String)
  fullName.vb: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.New(String)
  name.vb: New(String)
- uid: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.UserId
  commentId: P:CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.UserId
  id: UserId
  parent: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery
  langs:
  - csharp
  - vb
  name: UserId
  nameWithType: GetLatestWeightMeasurementQuery.UserId
  fullName: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.UserId
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/WeightMeasurements/Queries/GetLatestWeightMeasurementQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: UserId
    path: ../src/CalorieTracker.Application/WeightMeasurements/Queries/GetLatestWeightMeasurementQuery.cs
    startLine: 15
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.WeightMeasurements.Queries
  syntax:
    content: public string UserId { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property UserId As String
  overload: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.UserId*
references:
- uid: CalorieTracker.Application.WeightMeasurements.Queries
  commentId: N:CalorieTracker.Application.WeightMeasurements.Queries
  href: CalorieTracker.html
  name: CalorieTracker.Application.WeightMeasurements.Queries
  nameWithType: CalorieTracker.Application.WeightMeasurements.Queries
  fullName: CalorieTracker.Application.WeightMeasurements.Queries
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.WeightMeasurements
    name: WeightMeasurements
    href: CalorieTracker.Application.WeightMeasurements.html
  - name: .
  - uid: CalorieTracker.Application.WeightMeasurements.Queries
    name: Queries
    href: CalorieTracker.Application.WeightMeasurements.Queries.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.WeightMeasurements
    name: WeightMeasurements
    href: CalorieTracker.Application.WeightMeasurements.html
  - name: .
  - uid: CalorieTracker.Application.WeightMeasurements.Queries
    name: Queries
    href: CalorieTracker.Application.WeightMeasurements.Queries.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.IEquatable{CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery}
  commentId: T:System.IEquatable{CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<GetLatestWeightMeasurementQuery>
  nameWithType: IEquatable<GetLatestWeightMeasurementQuery>
  fullName: System.IEquatable<CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery>
  nameWithType.vb: IEquatable(Of GetLatestWeightMeasurementQuery)
  fullName.vb: System.IEquatable(Of CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery)
  name.vb: IEquatable(Of GetLatestWeightMeasurementQuery)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery
    name: GetLatestWeightMeasurementQuery
    href: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.html
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery
    name: GetLatestWeightMeasurementQuery
    href: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.html
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.#ctor*
  commentId: Overload:CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.#ctor
  href: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.html#CalorieTracker_Application_WeightMeasurements_Queries_GetLatestWeightMeasurementQuery__ctor_System_String_
  name: GetLatestWeightMeasurementQuery
  nameWithType: GetLatestWeightMeasurementQuery.GetLatestWeightMeasurementQuery
  fullName: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.GetLatestWeightMeasurementQuery
  nameWithType.vb: GetLatestWeightMeasurementQuery.New
  fullName.vb: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.UserId*
  commentId: Overload:CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.UserId
  href: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.html#CalorieTracker_Application_WeightMeasurements_Queries_GetLatestWeightMeasurementQuery_UserId
  name: UserId
  nameWithType: GetLatestWeightMeasurementQuery.UserId
  fullName: CalorieTracker.Application.WeightMeasurements.Queries.GetLatestWeightMeasurementQuery.UserId
