### YamlMime:ManagedReference
items:
- uid: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand
  commentId: T:CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand
  id: CreateRecipeIngredientCommand
  parent: CalorieTracker.Application.Recipes.Commands
  children:
  - CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.ProductId
  - CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.Quantity
  langs:
  - csharp
  - vb
  name: CreateRecipeIngredientCommand
  nameWithType: CreateRecipeIngredientCommand
  fullName: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand
  type: Class
  source:
    remote:
      path: src/CalorieTracker.Application/Recipes/Commands/CreateRecipeIngredientCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: CreateRecipeIngredientCommand
    path: ../src/CalorieTracker.Application/Recipes/Commands/CreateRecipeIngredientCommand.cs
    startLine: 13
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Recipes.Commands
  summary: >-
    Rekord reprezentujący komendę tworzenia składnika w przepisie kulinarnym.

    Zawiera informacje o produkcie i jego ilości potrzebnej w przepisie.
  remarks: >-
    Wykorzystanie typu record zapewnia niezmienność danych transferowych.

    Stanowi część składową komendy <xref href="CalorieTracker.Application.Recipes.Commands.CreateRecipeCommand" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: 'public record CreateRecipeIngredientCommand : IEquatable<CreateRecipeIngredientCommand>'
    content.vb: Public Class CreateRecipeIngredientCommand Implements IEquatable(Of CreateRecipeIngredientCommand)
  inheritance:
  - System.Object
  implements:
  - System.IEquatable{CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand}
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.ProductId
  commentId: P:CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.ProductId
  id: ProductId
  parent: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand
  langs:
  - csharp
  - vb
  name: ProductId
  nameWithType: CreateRecipeIngredientCommand.ProductId
  fullName: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.ProductId
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Recipes/Commands/CreateRecipeIngredientCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: ProductId
    path: ../src/CalorieTracker.Application/Recipes/Commands/CreateRecipeIngredientCommand.cs
    startLine: 21
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Recipes.Commands
  summary: Identyfikator produktu użytego jako składnik
  example: []
  syntax:
    content: public Guid ProductId { get; init; }
    parameters: []
    return:
      type: System.Guid
      description: Wartość typu Guid reprezentująca unikalny identyfikator istniejącego produktu w systemie.
    content.vb: Public Property ProductId As Guid
  overload: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.ProductId*
- uid: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.Quantity
  commentId: P:CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.Quantity
  id: Quantity
  parent: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand
  langs:
  - csharp
  - vb
  name: Quantity
  nameWithType: CreateRecipeIngredientCommand.Quantity
  fullName: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.Quantity
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Recipes/Commands/CreateRecipeIngredientCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Quantity
    path: ../src/CalorieTracker.Application/Recipes/Commands/CreateRecipeIngredientCommand.cs
    startLine: 30
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Recipes.Commands
  summary: Ilość produktu w składniku przepisu
  example: []
  syntax:
    content: public float Quantity { get; init; }
    parameters: []
    return:
      type: System.Single
      description: >-
        Wartość zmiennoprzecinkowa określająca ilość produktu potrzebną w przepisie.

        Wartość musi być dodatnia.
    content.vb: Public Property Quantity As Single
  overload: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.Quantity*
references:
- uid: CalorieTracker.Application.Recipes.Commands.CreateRecipeCommand
  commentId: T:CalorieTracker.Application.Recipes.Commands.CreateRecipeCommand
  parent: CalorieTracker.Application.Recipes.Commands
  href: CalorieTracker.Application.Recipes.Commands.CreateRecipeCommand.html
  name: CreateRecipeCommand
  nameWithType: CreateRecipeCommand
  fullName: CalorieTracker.Application.Recipes.Commands.CreateRecipeCommand
- uid: CalorieTracker.Application.Recipes.Commands
  commentId: N:CalorieTracker.Application.Recipes.Commands
  href: CalorieTracker.html
  name: CalorieTracker.Application.Recipes.Commands
  nameWithType: CalorieTracker.Application.Recipes.Commands
  fullName: CalorieTracker.Application.Recipes.Commands
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Recipes
    name: Recipes
    href: CalorieTracker.Application.Recipes.html
  - name: .
  - uid: CalorieTracker.Application.Recipes.Commands
    name: Commands
    href: CalorieTracker.Application.Recipes.Commands.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Recipes
    name: Recipes
    href: CalorieTracker.Application.Recipes.html
  - name: .
  - uid: CalorieTracker.Application.Recipes.Commands
    name: Commands
    href: CalorieTracker.Application.Recipes.Commands.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.IEquatable{CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand}
  commentId: T:System.IEquatable{CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<CreateRecipeIngredientCommand>
  nameWithType: IEquatable<CreateRecipeIngredientCommand>
  fullName: System.IEquatable<CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand>
  nameWithType.vb: IEquatable(Of CreateRecipeIngredientCommand)
  fullName.vb: System.IEquatable(Of CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand)
  name.vb: IEquatable(Of CreateRecipeIngredientCommand)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand
    name: CreateRecipeIngredientCommand
    href: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.html
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand
    name: CreateRecipeIngredientCommand
    href: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.html
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.ProductId*
  commentId: Overload:CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.ProductId
  href: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.html#CalorieTracker_Application_Recipes_Commands_CreateRecipeIngredientCommand_ProductId
  name: ProductId
  nameWithType: CreateRecipeIngredientCommand.ProductId
  fullName: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.ProductId
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.Quantity*
  commentId: Overload:CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.Quantity
  href: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.html#CalorieTracker_Application_Recipes_Commands_CreateRecipeIngredientCommand_Quantity
  name: Quantity
  nameWithType: CreateRecipeIngredientCommand.Quantity
  fullName: CalorieTracker.Application.Recipes.Commands.CreateRecipeIngredientCommand.Quantity
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
