### YamlMime:ManagedReference
items:
- uid: CalorieTracker.Application.Auth.Commands.DeleteProductCommand
  commentId: T:CalorieTracker.Application.Auth.Commands.DeleteProductCommand
  id: DeleteProductCommand
  parent: CalorieTracker.Application.Auth.Commands
  children:
  - CalorieTracker.Application.Auth.Commands.DeleteProductCommand.#ctor(System.Guid,System.String)
  - CalorieTracker.Application.Auth.Commands.DeleteProductCommand.DeletedByUserId
  - CalorieTracker.Application.Auth.Commands.DeleteProductCommand.Id
  langs:
  - csharp
  - vb
  name: DeleteProductCommand
  nameWithType: DeleteProductCommand
  fullName: CalorieTracker.Application.Auth.Commands.DeleteProductCommand
  type: Class
  source:
    remote:
      path: src/CalorieTracker.Application/Products/Commands/DeleteProductCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: DeleteProductCommand
    path: ../src/CalorieTracker.Application/Products/Commands/DeleteProductCommand.cs
    startLine: 11
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Commands
  summary: >-
    Rekord reprezentujący komendę usuwania produktu spożywczego.

    Zawiera identyfikator produktu oraz informację o użytkowniku wykonującym operację.
  example: []
  syntax:
    content: 'public record DeleteProductCommand : IEquatable<DeleteProductCommand>'
    content.vb: Public Class DeleteProductCommand Implements IEquatable(Of DeleteProductCommand)
  inheritance:
  - System.Object
  implements:
  - System.IEquatable{CalorieTracker.Application.Auth.Commands.DeleteProductCommand}
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.#ctor(System.Guid,System.String)
  commentId: M:CalorieTracker.Application.Auth.Commands.DeleteProductCommand.#ctor(System.Guid,System.String)
  id: '#ctor(System.Guid,System.String)'
  parent: CalorieTracker.Application.Auth.Commands.DeleteProductCommand
  langs:
  - csharp
  - vb
  name: DeleteProductCommand(Guid, string)
  nameWithType: DeleteProductCommand.DeleteProductCommand(Guid, string)
  fullName: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.DeleteProductCommand(System.Guid, string)
  type: Constructor
  source:
    remote:
      path: src/CalorieTracker.Application/Products/Commands/DeleteProductCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: .ctor
    path: ../src/CalorieTracker.Application/Products/Commands/DeleteProductCommand.cs
    startLine: 11
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Commands
  summary: >-
    Rekord reprezentujący komendę usuwania produktu spożywczego.

    Zawiera identyfikator produktu oraz informację o użytkowniku wykonującym operację.
  example: []
  syntax:
    content: public DeleteProductCommand(Guid Id, string DeletedByUserId)
    parameters:
    - id: Id
      type: System.Guid
      description: Unikalny identyfikator produktu do usunięcia.
    - id: DeletedByUserId
      type: System.String
      description: Identyfikator użytkownika wykonującego operację usunięcia.
    content.vb: Public Sub New(Id As Guid, DeletedByUserId As String)
  overload: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.#ctor*
  nameWithType.vb: DeleteProductCommand.New(Guid, String)
  fullName.vb: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.New(System.Guid, String)
  name.vb: New(Guid, String)
- uid: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.Id
  commentId: P:CalorieTracker.Application.Auth.Commands.DeleteProductCommand.Id
  id: Id
  parent: CalorieTracker.Application.Auth.Commands.DeleteProductCommand
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: DeleteProductCommand.Id
  fullName: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.Id
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Products/Commands/DeleteProductCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Id
    path: ../src/CalorieTracker.Application/Products/Commands/DeleteProductCommand.cs
    startLine: 11
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Commands
  summary: Unikalny identyfikator produktu do usunięcia.
  example: []
  syntax:
    content: public Guid Id { get; init; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.Id*
- uid: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.DeletedByUserId
  commentId: P:CalorieTracker.Application.Auth.Commands.DeleteProductCommand.DeletedByUserId
  id: DeletedByUserId
  parent: CalorieTracker.Application.Auth.Commands.DeleteProductCommand
  langs:
  - csharp
  - vb
  name: DeletedByUserId
  nameWithType: DeleteProductCommand.DeletedByUserId
  fullName: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.DeletedByUserId
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Products/Commands/DeleteProductCommand.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: DeletedByUserId
    path: ../src/CalorieTracker.Application/Products/Commands/DeleteProductCommand.cs
    startLine: 11
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Commands
  summary: Identyfikator użytkownika wykonującego operację usunięcia.
  example: []
  syntax:
    content: public string DeletedByUserId { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property DeletedByUserId As String
  overload: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.DeletedByUserId*
references:
- uid: CalorieTracker.Application.Auth.Commands
  commentId: N:CalorieTracker.Application.Auth.Commands
  href: CalorieTracker.html
  name: CalorieTracker.Application.Auth.Commands
  nameWithType: CalorieTracker.Application.Auth.Commands
  fullName: CalorieTracker.Application.Auth.Commands
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Commands
    name: Commands
    href: CalorieTracker.Application.Auth.Commands.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Commands
    name: Commands
    href: CalorieTracker.Application.Auth.Commands.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.IEquatable{CalorieTracker.Application.Auth.Commands.DeleteProductCommand}
  commentId: T:System.IEquatable{CalorieTracker.Application.Auth.Commands.DeleteProductCommand}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<DeleteProductCommand>
  nameWithType: IEquatable<DeleteProductCommand>
  fullName: System.IEquatable<CalorieTracker.Application.Auth.Commands.DeleteProductCommand>
  nameWithType.vb: IEquatable(Of DeleteProductCommand)
  fullName.vb: System.IEquatable(Of CalorieTracker.Application.Auth.Commands.DeleteProductCommand)
  name.vb: IEquatable(Of DeleteProductCommand)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: CalorieTracker.Application.Auth.Commands.DeleteProductCommand
    name: DeleteProductCommand
    href: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.html
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: CalorieTracker.Application.Auth.Commands.DeleteProductCommand
    name: DeleteProductCommand
    href: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.html
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.#ctor*
  commentId: Overload:CalorieTracker.Application.Auth.Commands.DeleteProductCommand.#ctor
  href: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.html#CalorieTracker_Application_Auth_Commands_DeleteProductCommand__ctor_System_Guid_System_String_
  name: DeleteProductCommand
  nameWithType: DeleteProductCommand.DeleteProductCommand
  fullName: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.DeleteProductCommand
  nameWithType.vb: DeleteProductCommand.New
  fullName.vb: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.New
  name.vb: New
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.Id*
  commentId: Overload:CalorieTracker.Application.Auth.Commands.DeleteProductCommand.Id
  href: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.html#CalorieTracker_Application_Auth_Commands_DeleteProductCommand_Id
  name: Id
  nameWithType: DeleteProductCommand.Id
  fullName: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.Id
- uid: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.DeletedByUserId*
  commentId: Overload:CalorieTracker.Application.Auth.Commands.DeleteProductCommand.DeletedByUserId
  href: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.html#CalorieTracker_Application_Auth_Commands_DeleteProductCommand_DeletedByUserId
  name: DeletedByUserId
  nameWithType: DeleteProductCommand.DeletedByUserId
  fullName: CalorieTracker.Application.Auth.Commands.DeleteProductCommand.DeletedByUserId
