### YamlMime:ManagedReference
items:
- uid: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery
  commentId: T:CalorieTracker.Application.Auth.Queries.GetUserProductsQuery
  id: GetUserProductsQuery
  parent: CalorieTracker.Application.Auth.Queries
  children:
  - CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Skip
  - CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Take
  - CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.UserId
  langs:
  - csharp
  - vb
  name: GetUserProductsQuery
  nameWithType: GetUserProductsQuery
  fullName: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery
  type: Class
  source:
    remote:
      path: src/CalorieTracker.Application/Products/Queries/GetUserProductsQuerry.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: GetUserProductsQuery
    path: ../src/CalorieTracker.Application/Products/Queries/GetUserProductsQuerry.cs
    startLine: 19
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Queries
  summary: >-
    Klasa reprezentująca zapytanie o pobranie produktów powiązanych z określonym użytkownikiem.

    Zawiera parametry paginacji oraz identyfikator użytkownika.
  remarks: >-
    Implementacja jako klasy (zamiast record) pozwala na domyślne wartości właściwości.

    Właściwości init-only zapewniają niezmienność obiektu po inicjalizacji.
  example: []
  syntax:
    content: public class GetUserProductsQuery
    content.vb: Public Class GetUserProductsQuery
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.UserId
  commentId: P:CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.UserId
  id: UserId
  parent: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery
  langs:
  - csharp
  - vb
  name: UserId
  nameWithType: GetUserProductsQuery.UserId
  fullName: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.UserId
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Products/Queries/GetUserProductsQuerry.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: UserId
    path: ../src/CalorieTracker.Application/Products/Queries/GetUserProductsQuerry.cs
    startLine: 28
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Queries
  summary: Identyfikator użytkownika, dla którego pobierane są produkty
  example: []
  syntax:
    content: public string UserId { get; init; }
    parameters: []
    return:
      type: System.String
      description: >-
        Ciąg znaków reprezentujący unikalny identyfikator użytkownika w systemie.

        Wartość musi być różna od null.
    content.vb: Public Property UserId As String
  overload: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.UserId*
- uid: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Skip
  commentId: P:CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Skip
  id: Skip
  parent: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery
  langs:
  - csharp
  - vb
  name: Skip
  nameWithType: GetUserProductsQuery.Skip
  fullName: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Skip
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Products/Queries/GetUserProductsQuerry.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Skip
    path: ../src/CalorieTracker.Application/Products/Queries/GetUserProductsQuerry.cs
    startLine: 36
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Queries
  summary: Liczba produktów do pominięcia (stronicowanie)
  example: []
  syntax:
    content: public int Skip { get; init; }
    parameters: []
    return:
      type: System.Int32
      description: 'Domyślna wartość: 0. Pozwala na implementację mechanizmu paginacji.'
    content.vb: Public Property Skip As Integer
  overload: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Skip*
- uid: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Take
  commentId: P:CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Take
  id: Take
  parent: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery
  langs:
  - csharp
  - vb
  name: Take
  nameWithType: GetUserProductsQuery.Take
  fullName: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Take
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Products/Queries/GetUserProductsQuerry.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Take
    path: ../src/CalorieTracker.Application/Products/Queries/GetUserProductsQuerry.cs
    startLine: 44
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Queries
  summary: Maksymalna liczba produktów do pobrania (stronicowanie)
  example: []
  syntax:
    content: public int Take { get; init; }
    parameters: []
    return:
      type: System.Int32
      description: 'Domyślna wartość: 20. Określa rozmiar strony wyników.'
    content.vb: Public Property Take As Integer
  overload: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Take*
references:
- uid: CalorieTracker.Application.Auth.Queries
  commentId: N:CalorieTracker.Application.Auth.Queries
  href: CalorieTracker.html
  name: CalorieTracker.Application.Auth.Queries
  nameWithType: CalorieTracker.Application.Auth.Queries
  fullName: CalorieTracker.Application.Auth.Queries
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Queries
    name: Queries
    href: CalorieTracker.Application.Auth.Queries.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Queries
    name: Queries
    href: CalorieTracker.Application.Auth.Queries.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.UserId*
  commentId: Overload:CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.UserId
  href: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.html#CalorieTracker_Application_Auth_Queries_GetUserProductsQuery_UserId
  name: UserId
  nameWithType: GetUserProductsQuery.UserId
  fullName: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.UserId
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Skip*
  commentId: Overload:CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Skip
  href: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.html#CalorieTracker_Application_Auth_Queries_GetUserProductsQuery_Skip
  name: Skip
  nameWithType: GetUserProductsQuery.Skip
  fullName: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Skip
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Take*
  commentId: Overload:CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Take
  href: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.html#CalorieTracker_Application_Auth_Queries_GetUserProductsQuery_Take
  name: Take
  nameWithType: GetUserProductsQuery.Take
  fullName: CalorieTracker.Application.Auth.Queries.GetUserProductsQuery.Take
