### YamlMime:ManagedReference
items:
- uid: CalorieTracker.Application.Auth.Queries.LoginUserQuery
  commentId: T:CalorieTracker.Application.Auth.Queries.LoginUserQuery
  id: LoginUserQuery
  parent: CalorieTracker.Application.Auth.Queries
  children:
  - CalorieTracker.Application.Auth.Queries.LoginUserQuery.Email
  - CalorieTracker.Application.Auth.Queries.LoginUserQuery.Password
  langs:
  - csharp
  - vb
  name: LoginUserQuery
  nameWithType: LoginUserQuery
  fullName: CalorieTracker.Application.Auth.Queries.LoginUserQuery
  type: Class
  source:
    remote:
      path: src/CalorieTracker.Application/Auth/Queries/LoginUserQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: LoginUserQuery
    path: ../src/CalorieTracker.Application/Auth/Queries/LoginUserQuery.cs
    startLine: 9
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Queries
  summary: >-
    Rekord reprezentujący zapytanie logowania użytkownika.

    Zawiera dane uwierzytelniające wymagane do procesu logowania.
  example: []
  syntax:
    content: public class LoginUserQuery
    content.vb: Public Class LoginUserQuery
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CalorieTracker.Application.Auth.Queries.LoginUserQuery.Email
  commentId: P:CalorieTracker.Application.Auth.Queries.LoginUserQuery.Email
  id: Email
  parent: CalorieTracker.Application.Auth.Queries.LoginUserQuery
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: LoginUserQuery.Email
  fullName: CalorieTracker.Application.Auth.Queries.LoginUserQuery.Email
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Auth/Queries/LoginUserQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Email
    path: ../src/CalorieTracker.Application/Auth/Queries/LoginUserQuery.cs
    startLine: 14
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Queries
  summary: Adres email użytkownika wykorzystywany do logowania.
  example: []
  syntax:
    content: public string Email { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Email As String
  overload: CalorieTracker.Application.Auth.Queries.LoginUserQuery.Email*
- uid: CalorieTracker.Application.Auth.Queries.LoginUserQuery.Password
  commentId: P:CalorieTracker.Application.Auth.Queries.LoginUserQuery.Password
  id: Password
  parent: CalorieTracker.Application.Auth.Queries.LoginUserQuery
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: LoginUserQuery.Password
  fullName: CalorieTracker.Application.Auth.Queries.LoginUserQuery.Password
  type: Property
  source:
    remote:
      path: src/CalorieTracker.Application/Auth/Queries/LoginUserQuery.cs
      branch: main
      repo: https://github.com/TexablePlum/CalorieTracker.git
    id: Password
    path: ../src/CalorieTracker.Application/Auth/Queries/LoginUserQuery.cs
    startLine: 19
  assemblies:
  - CalorieTracker.Application
  namespace: CalorieTracker.Application.Auth.Queries
  summary: Hasło użytkownika wymagane do uwierzytelnienia.
  example: []
  syntax:
    content: public string Password { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Password As String
  overload: CalorieTracker.Application.Auth.Queries.LoginUserQuery.Password*
references:
- uid: CalorieTracker.Application.Auth.Queries
  commentId: N:CalorieTracker.Application.Auth.Queries
  href: CalorieTracker.html
  name: CalorieTracker.Application.Auth.Queries
  nameWithType: CalorieTracker.Application.Auth.Queries
  fullName: CalorieTracker.Application.Auth.Queries
  spec.csharp:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Queries
    name: Queries
    href: CalorieTracker.Application.Auth.Queries.html
  spec.vb:
  - uid: CalorieTracker
    name: CalorieTracker
    href: CalorieTracker.html
  - name: .
  - uid: CalorieTracker.Application
    name: Application
    href: CalorieTracker.Application.html
  - name: .
  - uid: CalorieTracker.Application.Auth
    name: Auth
    href: CalorieTracker.Application.Auth.html
  - name: .
  - uid: CalorieTracker.Application.Auth.Queries
    name: Queries
    href: CalorieTracker.Application.Auth.Queries.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CalorieTracker.Application.Auth.Queries.LoginUserQuery.Email*
  commentId: Overload:CalorieTracker.Application.Auth.Queries.LoginUserQuery.Email
  href: CalorieTracker.Application.Auth.Queries.LoginUserQuery.html#CalorieTracker_Application_Auth_Queries_LoginUserQuery_Email
  name: Email
  nameWithType: LoginUserQuery.Email
  fullName: CalorieTracker.Application.Auth.Queries.LoginUserQuery.Email
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CalorieTracker.Application.Auth.Queries.LoginUserQuery.Password*
  commentId: Overload:CalorieTracker.Application.Auth.Queries.LoginUserQuery.Password
  href: CalorieTracker.Application.Auth.Queries.LoginUserQuery.html#CalorieTracker_Application_Auth_Queries_LoginUserQuery_Password
  name: Password
  nameWithType: LoginUserQuery.Password
  fullName: CalorieTracker.Application.Auth.Queries.LoginUserQuery.Password
